# Site settings
title: TyOc Labs
email: contact@tyoc.mx
description: > # Tleyotl Ocelocoatl labs
  Discovering the unknow exploring the borders of the know realms.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tyoc.mx" # the base hostname & protocol for your site
twitter_username: 
github_username:  tleyotlocelocoatl

# Build settings
markdown: kramdown
